use_frameworks!

target 'Blackhole Example' do
  pod 'Blackhole/BrightFutures', :path => '../'

  target 'Blackhole Tests' do
    pod 'Blackhole/BrightFutures', :path => '../'
    inherit! :search_paths

  end
end
